### PR TITLE
Fix the issue 196

### LINKED ISSUE #196: 4.0.0 no longer included in "check"
If I update the plugin version from 3.0.0 to 4.0.0, `spotbugMain` and `spotBugsTest` no longer run as part of the `check` task.  They work if I run the tasks manually, but they used to be included as a verification step.  I looked through the changelog and did not see anything.  Was this intentional?

### PR DESCRIPTION
**Pull request by KengoTODA**
close #196

### CODE REVIEW

File: src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java [hunk 1]
```diff
@@ -18,13 +18,17 @@
...
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 public class SpotBugsPlugin implements Plugin<Project> {
   public static final String CONFIG_NAME = "spotbugs";
   public static final String PLUGINS_CONFIG_NAME = "spotbugsPlugins";
   public static final String SLF4J_CONFIG_NAME = "spotbugsSlf4j";
   public static final String EXTENSION_NAME = "spotbugs";
 
+  private final Logger log = LoggerFactory.getLogger(SpotBugsPlugin.class);
```
Comment (ThrawnCA) [inline src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java]: This could instead be `LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());` so that it can be copy-pasted to other classes. Also, why not `static`?

Comment (KengoTODA) [reply src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java]: I'm not so positive to make copy-paste friendly in this case. The code  with `MethodHandles` isn't so intentional.

To avoid the pointed mistake, since we use JDK11 to build in CI, I wanna use Errorprone with [SLF4J plugin](https://github.com/KengoTODA/errorprone-slf4j) that can detect it. I'll make separated PR.

> Also, why not static?

It simply has no merit nor demerit. `Plugin` instance is created just few times per build.

Comment (KengoTODA) [reply src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java]: Ouch, we code in Groovy so Errorprone doesn't work. Now it's time to use SpotBugs! :)

Comment (ThrawnCA) [reply src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java]: Note that PMD will flag non-static loggers as a mistake unless passed into the constructor: https://pmd.github.io/latest/pmd_rules_java_errorprone.html#properlogger

Why not make logging statements copy-paste friendly? They're gonna be copy-pasted at some point, may as well avoid the risk of forgetting to update the classname.

Comment (KengoTODA) [reply src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java]: Confirmed that SpotBugs SLF4J plugin cannot detect the issue, because Groovy compiles this code into the following format:

```
        Object var5 = var4[0].call(LoggerFactory.class, Object.class);
        this.log = (Logger)ScriptBytecodeAdapter.castToType(var5, Logger.class);
```

so I'll follow your suggestion at this moment.

Comment (KengoTODA) [reply src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java]: > Why not make logging statements copy-paste friendly?

I believe it's not the way to go. And if I do, I will choose `LoggerFactory.getLogger(getClass())` which is more intuitive code to read.

BTW static-or-not is not so problem, [FAQ says both are OK](http://www.slf4j.org/faq.html#declared_static). Then I personally prefer the less-magic way.

Comment (ThrawnCA) [reply src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java]: `getClass()` works for an instance logger, yes.
